language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install: "test $TRAVIS_NODE_VERSION = '0.8' && npm install -g npm@1.2.8000 || true"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export NODE_PATH="$NVM_PATH/../node_modules"
